language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

before_install:
  - pip install pip --upgrade
  - pip install flake8
  - pip install coverage

install:
  - python setup.py install

script:
  - flake8
  - python setup.py test
  - coverage run --source='.' setup.py test
  - coverage report -m --skip-covered
